# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'empa_guiGEwcDO.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFrame, QGroupBox,
    QLabel, QLineEdit, QMainWindow, QMenuBar,
    QPushButton, QSizePolicy, QStatusBar, QTabWidget,
    QWidget)

class Ui_EmpaGUI(object):
    def setupUi(self, EmpaGUI):
        if not EmpaGUI.objectName():
            EmpaGUI.setObjectName(u"EmpaGUI")
        EmpaGUI.resize(431, 472)
        self.centralwidget = QWidget(EmpaGUI)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 441, 421))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.groupBox = QGroupBox(self.tab)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(0, 0, 431, 111))
        self.load_data_path = QLineEdit(self.groupBox)
        self.load_data_path.setObjectName(u"load_data_path")
        self.load_data_path.setGeometry(QRect(10, 20, 331, 22))
        self.Brows_data_folder_button = QPushButton(self.groupBox)
        self.Brows_data_folder_button.setObjectName(u"Brows_data_folder_button")
        self.Brows_data_folder_button.setGeometry(QRect(334, 20, 91, 24))
        self.load_data_plate_type_dropdown = QComboBox(self.groupBox)
        self.load_data_plate_type_dropdown.addItem("")
        self.load_data_plate_type_dropdown.addItem("")
        self.load_data_plate_type_dropdown.setObjectName(u"load_data_plate_type_dropdown")
        self.load_data_plate_type_dropdown.setGeometry(QRect(80, 50, 341, 24))
        self.load_data_button = QPushButton(self.groupBox)
        self.load_data_button.setObjectName(u"load_data_button")
        self.load_data_button.setGeometry(QRect(0, 80, 421, 24))
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 54, 71, 16))
        self.groupBox_2 = QGroupBox(self.tab)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(0, 110, 431, 151))
        self.load_model_button = QPushButton(self.groupBox_2)
        self.load_model_button.setObjectName(u"load_model_button")
        self.load_model_button.setGeometry(QRect(10, 50, 411, 24))
        self.train_dropdown = QComboBox(self.groupBox_2)
        self.train_dropdown.addItem("")
        self.train_dropdown.addItem("")
        self.train_dropdown.setObjectName(u"train_dropdown")
        self.train_dropdown.setGeometry(QRect(10, 80, 401, 24))
        self.train_button = QPushButton(self.groupBox_2)
        self.train_button.setObjectName(u"train_button")
        self.train_button.setGeometry(QRect(10, 110, 329, 24))
        self.groupBox_3 = QGroupBox(self.tab)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(0, 260, 431, 51))
        self.predict_button = QPushButton(self.groupBox_3)
        self.predict_button.setObjectName(u"predict_button")
        self.predict_button.setGeometry(QRect(10, 20, 411, 24))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.tabWidget_2 = QTabWidget(self.tab_2)
        self.tabWidget_2.setObjectName(u"tabWidget_2")
        self.tabWidget_2.setGeometry(QRect(0, 0, 431, 391))
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.groupBox_4 = QGroupBox(self.tab_4)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(-1, 0, 421, 151))
        self.plot_plate_dropdown = QComboBox(self.groupBox_4)
        self.plot_plate_dropdown.setObjectName(u"plot_plate_dropdown")
        self.plot_plate_dropdown.setGeometry(QRect(60, 15, 361, 24))
        self.plot_segment_dropdown = QComboBox(self.groupBox_4)
        self.plot_segment_dropdown.setObjectName(u"plot_segment_dropdown")
        self.plot_segment_dropdown.setGeometry(QRect(60, 59, 361, 24))
        self.plot_button = QPushButton(self.groupBox_4)
        self.plot_button.setObjectName(u"plot_button")
        self.plot_button.setGeometry(QRect(10, 101, 201, 24))
        self.platre_data_button_2 = QPushButton(self.groupBox_4)
        self.platre_data_button_2.setObjectName(u"platre_data_button_2")
        self.platre_data_button_2.setGeometry(QRect(210, 101, 211, 24))
        self.Channel_segment_plot = QComboBox(self.groupBox_4)
        self.Channel_segment_plot.setObjectName(u"Channel_segment_plot")
        self.Channel_segment_plot.setGeometry(QRect(60, 80, 361, 24))
        self.type_of_signal_dropdown = QComboBox(self.groupBox_4)
        self.type_of_signal_dropdown.addItem("")
        self.type_of_signal_dropdown.addItem("")
        self.type_of_signal_dropdown.setObjectName(u"type_of_signal_dropdown")
        self.type_of_signal_dropdown.setGeometry(QRect(60, 37, 361, 24))
        self.label_2 = QLabel(self.groupBox_4)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(8, 18, 49, 16))
        self.label_3 = QLabel(self.groupBox_4)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(7, 38, 49, 16))
        self.label_4 = QLabel(self.groupBox_4)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(8, 61, 49, 16))
        self.label_5 = QLabel(self.groupBox_4)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(8, 82, 49, 16))
        self.unload_as_csv_button_data_button_3 = QPushButton(self.groupBox_4)
        self.unload_as_csv_button_data_button_3.setObjectName(u"unload_as_csv_button_data_button_3")
        self.unload_as_csv_button_data_button_3.setGeometry(QRect(10, 124, 201, 24))
        self.groupBox_5 = QGroupBox(self.tab_4)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(0, 150, 421, 211))
        self.calssification_plot_segment = QPushButton(self.groupBox_5)
        self.calssification_plot_segment.setObjectName(u"calssification_plot_segment")
        self.calssification_plot_segment.setGeometry(QRect(10, 15, 131, 24))
        self.groupBox_6 = QGroupBox(self.groupBox_5)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(0, 31, 411, 81))
        self.classification_set_category = QPushButton(self.groupBox_6)
        self.classification_set_category.setObjectName(u"classification_set_category")
        self.classification_set_category.setGeometry(QRect(300, 15, 101, 21))
        self.label_6 = QLabel(self.groupBox_6)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 18, 91, 16))
        self.label_6.setFrameShape(QFrame.Shape.Panel)
        self.label_7 = QLabel(self.groupBox_6)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(146, 40, 31, 16))
        self.label_8 = QLabel(self.groupBox_6)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(144, 18, 31, 16))
        self.label_9 = QLabel(self.groupBox_6)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 40, 31, 16))
        self.classification_labeling_start_element_text = QLineEdit(self.groupBox_6)
        self.classification_labeling_start_element_text.setObjectName(u"classification_labeling_start_element_text")
        self.classification_labeling_start_element_text.setGeometry(QRect(40, 35, 101, 22))
        self.classification_labeling_end_element_text = QLineEdit(self.groupBox_6)
        self.classification_labeling_end_element_text.setObjectName(u"classification_labeling_end_element_text")
        self.classification_labeling_end_element_text.setGeometry(QRect(173, 35, 121, 22))
        self.classification_labeling_label_text = QLineEdit(self.groupBox_6)
        self.classification_labeling_label_text.setObjectName(u"classification_labeling_label_text")
        self.classification_labeling_label_text.setGeometry(QRect(178, 11, 113, 22))
        self.classification_clear_labels_button = QPushButton(self.groupBox_6)
        self.classification_clear_labels_button.setObjectName(u"classification_clear_labels_button")
        self.classification_clear_labels_button.setGeometry(QRect(300, 35, 101, 21))
        self.calssification_segment_savetofolder_button = QPushButton(self.groupBox_6)
        self.calssification_segment_savetofolder_button.setObjectName(u"calssification_segment_savetofolder_button")
        self.calssification_segment_savetofolder_button.setGeometry(QRect(9, 56, 181, 24))
        self.groupBox_7 = QGroupBox(self.groupBox_5)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(1, 108, 411, 101))
        self.classification_run_classification_button = QPushButton(self.groupBox_7)
        self.classification_run_classification_button.setObjectName(u"classification_run_classification_button")
        self.classification_run_classification_button.setGeometry(QRect(300, 15, 101, 41))
        self.label_13 = QLabel(self.groupBox_7)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(8, 15, 41, 16))
        self.classificationclassifier_dropdown = QComboBox(self.groupBox_7)
        self.classificationclassifier_dropdown.addItem("")
        self.classificationclassifier_dropdown.setObjectName(u"classificationclassifier_dropdown")
        self.classificationclassifier_dropdown.setGeometry(QRect(49, 12, 251, 24))
        self.label_10 = QLabel(self.groupBox_7)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 40, 51, 16))
        self.classification_snippet_size_text = QLineEdit(self.groupBox_7)
        self.classification_snippet_size_text.setObjectName(u"classification_snippet_size_text")
        self.classification_snippet_size_text.setGeometry(QRect(56, 36, 71, 22))
        self.classification_preproc_dropdown = QComboBox(self.groupBox_7)
        self.classification_preproc_dropdown.addItem("")
        self.classification_preproc_dropdown.setObjectName(u"classification_preproc_dropdown")
        self.classification_preproc_dropdown.setGeometry(QRect(140, 36, 161, 24))
        self.label_11 = QLabel(self.groupBox_7)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 70, 51, 16))
        self.classification_test_text = QLineEdit(self.groupBox_7)
        self.classification_test_text.setObjectName(u"classification_test_text")
        self.classification_test_text.setGeometry(QRect(54, 66, 71, 22))
        self.classification_dataset_info_button = QPushButton(self.groupBox_7)
        self.classification_dataset_info_button.setObjectName(u"classification_dataset_info_button")
        self.classification_dataset_info_button.setGeometry(QRect(300, 56, 101, 41))
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        EmpaGUI.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(EmpaGUI)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 431, 33))
        EmpaGUI.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(EmpaGUI)
        self.statusbar.setObjectName(u"statusbar")
        EmpaGUI.setStatusBar(self.statusbar)

        self.retranslateUi(EmpaGUI)

        self.tabWidget.setCurrentIndex(0)
        self.load_data_plate_type_dropdown.setCurrentIndex(-1)
        self.classification_preproc_dropdown.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(EmpaGUI)
    # setupUi

    def retranslateUi(self, EmpaGUI):
        EmpaGUI.setWindowTitle(QCoreApplication.translate("EmpaGUI", u"MainWindow", None))
        self.groupBox.setTitle(QCoreApplication.translate("EmpaGUI", u"Train data source", None))
        self.Brows_data_folder_button.setText(QCoreApplication.translate("EmpaGUI", u"Browse folder", None))
        self.load_data_plate_type_dropdown.setItemText(0, QCoreApplication.translate("EmpaGUI", u"default", None))
        self.load_data_plate_type_dropdown.setItemText(1, QCoreApplication.translate("EmpaGUI", u"from file", None))

        self.load_data_plate_type_dropdown.setPlaceholderText(QCoreApplication.translate("EmpaGUI", u"Choose BPP type", None))
        self.load_data_button.setText(QCoreApplication.translate("EmpaGUI", u"Load data", None))
        self.label.setText(QCoreApplication.translate("EmpaGUI", u"Plate layout:", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("EmpaGUI", u"Model", None))
        self.load_model_button.setText(QCoreApplication.translate("EmpaGUI", u"Load pre-trained model", None))
        self.train_dropdown.setItemText(0, QCoreApplication.translate("EmpaGUI", u"autoencoder", None))
        self.train_dropdown.setItemText(1, QCoreApplication.translate("EmpaGUI", u"load from file", None))

        self.train_dropdown.setPlaceholderText(QCoreApplication.translate("EmpaGUI", u"Choose model architecture", None))
        self.train_button.setText(QCoreApplication.translate("EmpaGUI", u"Train model", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("EmpaGUI", u"GroupBox", None))
        self.predict_button.setText(QCoreApplication.translate("EmpaGUI", u"Run model (identify defects)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("EmpaGUI", u"Main", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("EmpaGUI", u"Segments", None))
        self.plot_plate_dropdown.setPlaceholderText(QCoreApplication.translate("EmpaGUI", u"Choose plate to plot", None))
        self.plot_segment_dropdown.setPlaceholderText(QCoreApplication.translate("EmpaGUI", u"Choose segment to plot", None))
        self.plot_button.setText(QCoreApplication.translate("EmpaGUI", u"Plot signal", None))
        self.platre_data_button_2.setText(QCoreApplication.translate("EmpaGUI", u"Segments - full list show", None))
        self.Channel_segment_plot.setPlaceholderText(QCoreApplication.translate("EmpaGUI", u"Choose channel to plot", None))
        self.type_of_signal_dropdown.setItemText(0, QCoreApplication.translate("EmpaGUI", u"Raw signals", None))
        self.type_of_signal_dropdown.setItemText(1, QCoreApplication.translate("EmpaGUI", u"Segments", None))

        self.type_of_signal_dropdown.setPlaceholderText(QCoreApplication.translate("EmpaGUI", u"Choose segment to plot", None))
        self.label_2.setText(QCoreApplication.translate("EmpaGUI", u"Plate:", None))
        self.label_3.setText(QCoreApplication.translate("EmpaGUI", u"Type:", None))
        self.label_4.setText(QCoreApplication.translate("EmpaGUI", u"Segment:", None))
        self.label_5.setText(QCoreApplication.translate("EmpaGUI", u"Channel:", None))
        self.unload_as_csv_button_data_button_3.setText(QCoreApplication.translate("EmpaGUI", u"Save as *.SCV", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("EmpaGUI", u"Classification (applicable only for segments)", None))
        self.calssification_plot_segment.setText(QCoreApplication.translate("EmpaGUI", u"Plot/update segment", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("EmpaGUI", u"Labeling", None))
        self.classification_set_category.setText(QCoreApplication.translate("EmpaGUI", u"Assign", None))
        self.label_6.setText(QCoreApplication.translate("EmpaGUI", u"Elements:", None))
        self.label_7.setText(QCoreApplication.translate("EmpaGUI", u"end-", None))
        self.label_8.setText(QCoreApplication.translate("EmpaGUI", u"label-", None))
        self.label_9.setText(QCoreApplication.translate("EmpaGUI", u"Start:", None))
        self.classification_clear_labels_button.setText(QCoreApplication.translate("EmpaGUI", u"Clear", None))
        self.calssification_segment_savetofolder_button.setText(QCoreApplication.translate("EmpaGUI", u" Labelled patterns to folder(.csv)", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("EmpaGUI", u"Classification train/test", None))
        self.classification_run_classification_button.setText(QCoreApplication.translate("EmpaGUI", u"Run", None))
        self.label_13.setText(QCoreApplication.translate("EmpaGUI", u"Model:", None))
        self.classificationclassifier_dropdown.setItemText(0, QCoreApplication.translate("EmpaGUI", u"XGBoost", None))

        self.classificationclassifier_dropdown.setPlaceholderText(QCoreApplication.translate("EmpaGUI", u"XGBoost", None))
        self.label_10.setText(QCoreApplication.translate("EmpaGUI", u"Snippet:", None))
        self.classification_snippet_size_text.setText(QCoreApplication.translate("EmpaGUI", u"1000", None))
        self.classification_preproc_dropdown.setItemText(0, QCoreApplication.translate("EmpaGUI", u"Preprocessing - none", None))

        self.classification_preproc_dropdown.setCurrentText(QCoreApplication.translate("EmpaGUI", u"Preprocessing - none", None))
        self.classification_preproc_dropdown.setPlaceholderText(QCoreApplication.translate("EmpaGUI", u"XGBoost", None))
        self.label_11.setText(QCoreApplication.translate("EmpaGUI", u"Test (%):", None))
        self.classification_test_text.setText(QCoreApplication.translate("EmpaGUI", u"20", None))
        self.classification_dataset_info_button.setText(QCoreApplication.translate("EmpaGUI", u"Dataset info", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), QCoreApplication.translate("EmpaGUI", u"Page 1", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), QCoreApplication.translate("EmpaGUI", u"Tab 2", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("EmpaGUI", u"Tools", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("EmpaGUI", u"Settings", None))
    # retranslateUi

