# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'empa_guiiDMVOM.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QGroupBox,
    QLabel, QLineEdit, QMainWindow, QMenuBar,
    QPushButton, QSizePolicy, QStatusBar, QTabWidget,
    QWidget)

class Ui_EmpaGUI(object):
    def setupUi(self, EmpaGUI):
        if not EmpaGUI.objectName():
            EmpaGUI.setObjectName(u"EmpaGUI")
        EmpaGUI.resize(431, 542)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(EmpaGUI.sizePolicy().hasHeightForWidth())
        EmpaGUI.setSizePolicy(sizePolicy)
        self.centralwidget = QWidget(EmpaGUI)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 80, 441, 401))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.groupBox = QGroupBox(self.tab)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(0, 0, 421, 111))
        self.load_data_path = QLineEdit(self.groupBox)
        self.load_data_path.setObjectName(u"load_data_path")
        self.load_data_path.setGeometry(QRect(10, 20, 311, 22))
        self.Brows_data_folder_button = QPushButton(self.groupBox)
        self.Brows_data_folder_button.setObjectName(u"Brows_data_folder_button")
        self.Brows_data_folder_button.setGeometry(QRect(323, 20, 91, 24))
        self.load_data_plate_type_dropdown = QComboBox(self.groupBox)
        self.load_data_plate_type_dropdown.addItem("")
        self.load_data_plate_type_dropdown.addItem("")
        self.load_data_plate_type_dropdown.addItem("")
        self.load_data_plate_type_dropdown.addItem("")
        self.load_data_plate_type_dropdown.addItem("")
        self.load_data_plate_type_dropdown.setObjectName(u"load_data_plate_type_dropdown")
        self.load_data_plate_type_dropdown.setGeometry(QRect(80, 50, 91, 24))
        self.load_data_button = QPushButton(self.groupBox)
        self.load_data_button.setObjectName(u"load_data_button")
        self.load_data_button.setGeometry(QRect(267, 45, 151, 61))
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 54, 71, 16))
        self.List_segments_names_button = QPushButton(self.groupBox)
        self.List_segments_names_button.setObjectName(u"List_segments_names_button")
        self.List_segments_names_button.setGeometry(QRect(173, 46, 91, 31))
        self.groupBox_3 = QGroupBox(self.tab)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(0, 110, 421, 71))
        self.real_time_source_dropdown_2 = QComboBox(self.groupBox_3)
        self.real_time_source_dropdown_2.addItem("")
        self.real_time_source_dropdown_2.addItem("")
        self.real_time_source_dropdown_2.setObjectName(u"real_time_source_dropdown_2")
        self.real_time_source_dropdown_2.setGeometry(QRect(10, 40, 301, 24))
        self.Brows_data_folder_button_2 = QPushButton(self.groupBox_3)
        self.Brows_data_folder_button_2.setObjectName(u"Brows_data_folder_button_2")
        self.Brows_data_folder_button_2.setGeometry(QRect(323, 14, 91, 24))
        self.real_time_folder_text = QLineEdit(self.groupBox_3)
        self.real_time_folder_text.setObjectName(u"real_time_folder_text")
        self.real_time_folder_text.setGeometry(QRect(7, 14, 311, 22))
        self.Start_real_time_button = QPushButton(self.tab)
        self.Start_real_time_button.setObjectName(u"Start_real_time_button")
        self.Start_real_time_button.setGeometry(QRect(0, 210, 211, 81))
        self.Stop_real_time_button_2 = QPushButton(self.tab)
        self.Stop_real_time_button_2.setObjectName(u"Stop_real_time_button_2")
        self.Stop_real_time_button_2.setGeometry(QRect(210, 210, 211, 81))
        self.label_18 = QLabel(self.tab)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(0, 190, 91, 16))
        self.Real_time_Frame_counter_label = QLabel(self.tab)
        self.Real_time_Frame_counter_label.setObjectName(u"Real_time_Frame_counter_label")
        self.Real_time_Frame_counter_label.setGeometry(QRect(84, 192, 91, 16))
        self.label_19 = QLabel(self.tab)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(190, 190, 41, 16))
        self.real_time_status_label = QLabel(self.tab)
        self.real_time_status_label.setObjectName(u"real_time_status_label")
        self.real_time_status_label.setGeometry(QRect(230, 190, 91, 16))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.tabWidget_2 = QTabWidget(self.tab_2)
        self.tabWidget_2.setObjectName(u"tabWidget_2")
        self.tabWidget_2.setGeometry(QRect(0, -3, 431, 381))
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.groupBox_4 = QGroupBox(self.tab_4)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(-1, -3, 421, 111))
        self.plot_plate_dropdown = QComboBox(self.groupBox_4)
        self.plot_plate_dropdown.setObjectName(u"plot_plate_dropdown")
        self.plot_plate_dropdown.setGeometry(QRect(61, 13, 221, 24))
        self.plot_segment_dropdown = QComboBox(self.groupBox_4)
        self.plot_segment_dropdown.setObjectName(u"plot_segment_dropdown")
        self.plot_segment_dropdown.setGeometry(QRect(60, 58, 221, 24))
        self.plot_button = QPushButton(self.groupBox_4)
        self.plot_button.setObjectName(u"plot_button")
        self.plot_button.setGeometry(QRect(280, 10, 71, 31))
        self.platre_data_button_2 = QPushButton(self.groupBox_4)
        self.platre_data_button_2.setObjectName(u"platre_data_button_2")
        self.platre_data_button_2.setGeometry(QRect(348, 10, 71, 31))
        self.Channel_segment_plot = QComboBox(self.groupBox_4)
        self.Channel_segment_plot.setObjectName(u"Channel_segment_plot")
        self.Channel_segment_plot.setGeometry(QRect(60, 80, 221, 24))
        self.type_of_signal_dropdown = QComboBox(self.groupBox_4)
        self.type_of_signal_dropdown.addItem("")
        self.type_of_signal_dropdown.addItem("")
        self.type_of_signal_dropdown.setObjectName(u"type_of_signal_dropdown")
        self.type_of_signal_dropdown.setGeometry(QRect(60, 36, 221, 24))
        self.label_2 = QLabel(self.groupBox_4)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(8, 18, 49, 16))
        self.label_3 = QLabel(self.groupBox_4)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(7, 38, 49, 16))
        self.label_4 = QLabel(self.groupBox_4)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(8, 61, 49, 16))
        self.label_5 = QLabel(self.groupBox_4)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(8, 82, 49, 16))
        self.unload_as_csv_button_data_button_3 = QPushButton(self.groupBox_4)
        self.unload_as_csv_button_data_button_3.setObjectName(u"unload_as_csv_button_data_button_3")
        self.unload_as_csv_button_data_button_3.setGeometry(QRect(280, 38, 81, 31))
        self.tools_show_scpetrogram_button = QPushButton(self.groupBox_4)
        self.tools_show_scpetrogram_button.setObjectName(u"tools_show_scpetrogram_button")
        self.tools_show_scpetrogram_button.setGeometry(QRect(280, 70, 51, 31))
        self.classification_preproc_dropdown_4 = QComboBox(self.groupBox_4)
        self.classification_preproc_dropdown_4.addItem("")
        self.classification_preproc_dropdown_4.setObjectName(u"classification_preproc_dropdown_4")
        self.classification_preproc_dropdown_4.setGeometry(QRect(330, 70, 71, 21))
        self.groupBox_5 = QGroupBox(self.tab_4)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(0, 102, 421, 241))
        self.groupBox_7 = QGroupBox(self.groupBox_5)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(2, 138, 401, 101))
        self.classification_run_classification_button = QPushButton(self.groupBox_7)
        self.classification_run_classification_button.setObjectName(u"classification_run_classification_button")
        self.classification_run_classification_button.setGeometry(QRect(287, 11, 101, 31))
        self.label_13 = QLabel(self.groupBox_7)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(8, 15, 41, 16))
        self.classificationclassifier_dropdown = QComboBox(self.groupBox_7)
        self.classificationclassifier_dropdown.addItem("")
        self.classificationclassifier_dropdown.addItem("")
        self.classificationclassifier_dropdown.addItem("")
        self.classificationclassifier_dropdown.addItem("")
        self.classificationclassifier_dropdown.addItem("")
        self.classificationclassifier_dropdown.addItem("")
        self.classificationclassifier_dropdown.addItem("")
        self.classificationclassifier_dropdown.addItem("")
        self.classificationclassifier_dropdown.addItem("")
        self.classificationclassifier_dropdown.addItem("")
        self.classificationclassifier_dropdown.setObjectName(u"classificationclassifier_dropdown")
        self.classificationclassifier_dropdown.setGeometry(QRect(59, 12, 221, 24))
        self.label_11 = QLabel(self.groupBox_7)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 70, 51, 16))
        self.classification_test_text = QLineEdit(self.groupBox_7)
        self.classification_test_text.setObjectName(u"classification_test_text")
        self.classification_test_text.setGeometry(QRect(58, 67, 71, 22))
        self.classification_dataset_info_button = QPushButton(self.groupBox_7)
        self.classification_dataset_info_button.setObjectName(u"classification_dataset_info_button")
        self.classification_dataset_info_button.setGeometry(QRect(285, 68, 101, 31))
        self.Classification_extract_save_features_to_file_button = QPushButton(self.groupBox_7)
        self.Classification_extract_save_features_to_file_button.setObjectName(u"Classification_extract_save_features_to_file_button")
        self.Classification_extract_save_features_to_file_button.setGeometry(QRect(160, 68, 121, 31))
        self.Classification_run_test_on_complete_segment_button = QPushButton(self.groupBox_7)
        self.Classification_run_test_on_complete_segment_button.setObjectName(u"Classification_run_test_on_complete_segment_button")
        self.Classification_run_test_on_complete_segment_button.setGeometry(QRect(285, 39, 101, 31))
        self.label_17 = QLabel(self.groupBox_7)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(7, 42, 51, 16))
        self.classification_preproc_dropdown_2 = QComboBox(self.groupBox_7)
        self.classification_preproc_dropdown_2.addItem("")
        self.classification_preproc_dropdown_2.addItem("")
        self.classification_preproc_dropdown_2.addItem("")
        self.classification_preproc_dropdown_2.setObjectName(u"classification_preproc_dropdown_2")
        self.classification_preproc_dropdown_2.setGeometry(QRect(60, 40, 221, 24))
        self.tabWidget_3 = QTabWidget(self.groupBox_5)
        self.tabWidget_3.setObjectName(u"tabWidget_3")
        self.tabWidget_3.setGeometry(QRect(0, 13, 411, 131))
        self.tab_12 = QWidget()
        self.tab_12.setObjectName(u"tab_12")
        self.groupBox_6 = QGroupBox(self.tab_12)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(0, -2, 401, 101))
        self.classification_set_category = QPushButton(self.groupBox_6)
        self.classification_set_category.setObjectName(u"classification_set_category")
        self.classification_set_category.setGeometry(QRect(250, 10, 71, 51))
        self.label_7 = QLabel(self.groupBox_6)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(160, 40, 31, 16))
        self.label_8 = QLabel(self.groupBox_6)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(150, 17, 31, 16))
        self.label_9 = QLabel(self.groupBox_6)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(60, 40, 31, 16))
        self.classification_labeling_start_element_text = QLineEdit(self.groupBox_6)
        self.classification_labeling_start_element_text.setObjectName(u"classification_labeling_start_element_text")
        self.classification_labeling_start_element_text.setGeometry(QRect(90, 39, 61, 22))
        self.classification_labeling_end_element_text = QLineEdit(self.groupBox_6)
        self.classification_labeling_end_element_text.setObjectName(u"classification_labeling_end_element_text")
        self.classification_labeling_end_element_text.setGeometry(QRect(180, 35, 71, 22))
        self.classification_labeling_label_text = QLineEdit(self.groupBox_6)
        self.classification_labeling_label_text.setObjectName(u"classification_labeling_label_text")
        self.classification_labeling_label_text.setGeometry(QRect(180, 13, 71, 22))
        self.classification_clear_labels_button = QPushButton(self.groupBox_6)
        self.classification_clear_labels_button.setObjectName(u"classification_clear_labels_button")
        self.classification_clear_labels_button.setGeometry(QRect(320, 10, 71, 31))
        self.calssification_segment_savetofolder_button = QPushButton(self.groupBox_6)
        self.calssification_segment_savetofolder_button.setObjectName(u"calssification_segment_savetofolder_button")
        self.calssification_segment_savetofolder_button.setGeometry(QRect(2, 59, 111, 41))
        self.classification_entire_segment_to_label_button = QPushButton(self.groupBox_6)
        self.classification_entire_segment_to_label_button.setObjectName(u"classification_entire_segment_to_label_button")
        self.classification_entire_segment_to_label_button.setGeometry(QRect(110, 59, 111, 41))
        self.classification_all_segments_to_label_button_2 = QPushButton(self.groupBox_6)
        self.classification_all_segments_to_label_button_2.setObjectName(u"classification_all_segments_to_label_button_2")
        self.classification_all_segments_to_label_button_2.setGeometry(QRect(219, 59, 131, 41))
        self.classification_clear_all_segments_labels_button_2 = QPushButton(self.groupBox_6)
        self.classification_clear_all_segments_labels_button_2.setObjectName(u"classification_clear_all_segments_labels_button_2")
        self.classification_clear_all_segments_labels_button_2.setGeometry(QRect(320, 40, 71, 21))
        self.calssification_plot_segment = QPushButton(self.groupBox_6)
        self.calssification_plot_segment.setObjectName(u"calssification_plot_segment")
        self.calssification_plot_segment.setGeometry(QRect(2, 11, 41, 31))
        self.classification_plot_choice_dropdown_3 = QComboBox(self.groupBox_6)
        self.classification_plot_choice_dropdown_3.addItem("")
        self.classification_plot_choice_dropdown_3.addItem("")
        self.classification_plot_choice_dropdown_3.setObjectName(u"classification_plot_choice_dropdown_3")
        self.classification_plot_choice_dropdown_3.setGeometry(QRect(44, 10, 101, 31))
        self.tabWidget_3.addTab(self.tab_12, "")
        self.tab_13 = QWidget()
        self.tab_13.setObjectName(u"tab_13")
        self.Classification_save_to_file_labeling_button = QPushButton(self.tab_13)
        self.Classification_save_to_file_labeling_button.setObjectName(u"Classification_save_to_file_labeling_button")
        self.Classification_save_to_file_labeling_button.setGeometry(QRect(0, 0, 131, 31))
        self.Classification_load_from_file_labeling_button_2 = QPushButton(self.tab_13)
        self.Classification_load_from_file_labeling_button_2.setObjectName(u"Classification_load_from_file_labeling_button_2")
        self.Classification_load_from_file_labeling_button_2.setGeometry(QRect(130, 0, 141, 31))
        self.groupBox_2 = QGroupBox(self.tab_13)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(0, 30, 401, 51))
        self.load_model_button = QPushButton(self.groupBox_2)
        self.load_model_button.setObjectName(u"load_model_button")
        self.load_model_button.setGeometry(QRect(243, 15, 151, 31))
        self.train_dropdown = QComboBox(self.groupBox_2)
        self.train_dropdown.addItem("")
        self.train_dropdown.addItem("")
        self.train_dropdown.setObjectName(u"train_dropdown")
        self.train_dropdown.setGeometry(QRect(78, 19, 161, 24))
        self.label_16 = QLabel(self.groupBox_2)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(10, 23, 71, 16))
        self.tabWidget_3.addTab(self.tab_13, "")
        self.tab_14 = QWidget()
        self.tab_14.setObjectName(u"tab_14")
        self.groupBox_17 = QGroupBox(self.tab_14)
        self.groupBox_17.setObjectName(u"groupBox_17")
        self.groupBox_17.setGeometry(QRect(0, 0, 401, 61))
        self.Classification_save__all_plates_segm_to_file_labeling_button_2 = QPushButton(self.groupBox_17)
        self.Classification_save__all_plates_segm_to_file_labeling_button_2.setObjectName(u"Classification_save__all_plates_segm_to_file_labeling_button_2")
        self.Classification_save__all_plates_segm_to_file_labeling_button_2.setGeometry(QRect(6, 20, 191, 31))
        self.Classification_load__all_plates_segm_to_file_labeling_button_2 = QPushButton(self.groupBox_17)
        self.Classification_load__all_plates_segm_to_file_labeling_button_2.setObjectName(u"Classification_load__all_plates_segm_to_file_labeling_button_2")
        self.Classification_load__all_plates_segm_to_file_labeling_button_2.setGeometry(QRect(196, 20, 201, 31))
        self.tabWidget_3.addTab(self.tab_14, "")
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.groupBox_18 = QGroupBox(self.tab_5)
        self.groupBox_18.setObjectName(u"groupBox_18")
        self.groupBox_18.setGeometry(QRect(0, 0, 421, 141))
        self.label_6 = QLabel(self.groupBox_18)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 60, 111, 16))
        self.Tool_start_best_param_search_button_2 = QPushButton(self.groupBox_18)
        self.Tool_start_best_param_search_button_2.setObjectName(u"Tool_start_best_param_search_button_2")
        self.Tool_start_best_param_search_button_2.setGeometry(QRect(10, 20, 191, 31))
        self.Tools_best_params_search_folder_path_text_2 = QLineEdit(self.groupBox_18)
        self.Tools_best_params_search_folder_path_text_2.setObjectName(u"Tools_best_params_search_folder_path_text_2")
        self.Tools_best_params_search_folder_path_text_2.setGeometry(QRect(110, 55, 241, 22))
        self.Brows_data_folder_button_3 = QPushButton(self.groupBox_18)
        self.Brows_data_folder_button_3.setObjectName(u"Brows_data_folder_button_3")
        self.Brows_data_folder_button_3.setGeometry(QRect(350, 55, 61, 24))
        self.label_33 = QLabel(self.groupBox_18)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(10, 85, 111, 16))
        self.Tools_best_params_search_snippet_size_start_text_3 = QLineEdit(self.groupBox_18)
        self.Tools_best_params_search_snippet_size_start_text_3.setObjectName(u"Tools_best_params_search_snippet_size_start_text_3")
        self.Tools_best_params_search_snippet_size_start_text_3.setGeometry(QRect(113, 82, 51, 22))
        self.label_34 = QLabel(self.groupBox_18)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(164, 85, 41, 16))
        self.Tools_best_params_search_snippet_size_end_text_3 = QLineEdit(self.groupBox_18)
        self.Tools_best_params_search_snippet_size_end_text_3.setObjectName(u"Tools_best_params_search_snippet_size_end_text_3")
        self.Tools_best_params_search_snippet_size_end_text_3.setGeometry(QRect(189, 82, 51, 22))
        self.label_35 = QLabel(self.groupBox_18)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(241, 86, 41, 16))
        self.Tools_best_params_search_snippet_size_step_text_3 = QLineEdit(self.groupBox_18)
        self.Tools_best_params_search_snippet_size_step_text_3.setObjectName(u"Tools_best_params_search_snippet_size_step_text_3")
        self.Tools_best_params_search_snippet_size_step_text_3.setGeometry(QRect(269, 82, 51, 22))
        self.label_36 = QLabel(self.groupBox_18)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(10, 113, 61, 16))
        self.Tools_best_params_search_channels_list_text_3 = QLineEdit(self.groupBox_18)
        self.Tools_best_params_search_channels_list_text_3.setObjectName(u"Tools_best_params_search_channels_list_text_3")
        self.Tools_best_params_search_channels_list_text_3.setGeometry(QRect(60, 110, 111, 22))
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.groupBox_8 = QGroupBox(self.tab_3)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(0, 0, 421, 81))
        self.label_12 = QLabel(self.groupBox_8)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 20, 171, 16))
        self.Settings_OpenFile_TrigChannelID_text = QLineEdit(self.groupBox_8)
        self.Settings_OpenFile_TrigChannelID_text.setObjectName(u"Settings_OpenFile_TrigChannelID_text")
        self.Settings_OpenFile_TrigChannelID_text.setGeometry(QRect(178, 16, 231, 22))
        self.Segmentlabel14 = QLabel(self.groupBox_8)
        self.Segmentlabel14.setObjectName(u"Segmentlabel14")
        self.Segmentlabel14.setGeometry(QRect(10, 50, 121, 16))
        self.Settings_openfile_segmentation_mode_text = QComboBox(self.groupBox_8)
        self.Settings_openfile_segmentation_mode_text.addItem("")
        self.Settings_openfile_segmentation_mode_text.addItem("")
        self.Settings_openfile_segmentation_mode_text.setObjectName(u"Settings_openfile_segmentation_mode_text")
        self.Settings_openfile_segmentation_mode_text.setGeometry(QRect(135, 47, 131, 24))
        self.Settings_Segmentation_TriggerThreshold_text = QLineEdit(self.groupBox_8)
        self.Settings_Segmentation_TriggerThreshold_text.setObjectName(u"Settings_Segmentation_TriggerThreshold_text")
        self.Settings_Segmentation_TriggerThreshold_text.setGeometry(QRect(270, 48, 131, 22))
        self.Settings_Spectrograms_Define_Parameters_Tab = QTabWidget(self.tab_3)
        self.Settings_Spectrograms_Define_Parameters_Tab.setObjectName(u"Settings_Spectrograms_Define_Parameters_Tab")
        self.Settings_Spectrograms_Define_Parameters_Tab.setGeometry(QRect(0, 80, 421, 311))
        self.tab_11 = QWidget()
        self.tab_11.setObjectName(u"tab_11")
        self.RealT_show_info_checkbox = QCheckBox(self.tab_11)
        self.RealT_show_info_checkbox.setObjectName(u"RealT_show_info_checkbox")
        self.RealT_show_info_checkbox.setGeometry(QRect(40, 170, 79, 20))
        self.RealT_show_info_checkbox.setChecked(True)
        self.RealT_show_processed_signals_checkbox_3 = QCheckBox(self.tab_11)
        self.RealT_show_processed_signals_checkbox_3.setObjectName(u"RealT_show_processed_signals_checkbox_3")
        self.RealT_show_processed_signals_checkbox_3.setGeometry(QRect(40, 190, 161, 20))
        self.RealT_show_only_single_shot_checkbox_4 = QCheckBox(self.tab_11)
        self.RealT_show_only_single_shot_checkbox_4.setObjectName(u"RealT_show_only_single_shot_checkbox_4")
        self.RealT_show_only_single_shot_checkbox_4.setGeometry(QRect(40, 210, 161, 20))
        self.RT_impose_delay_between_measurements_checkbox_3 = QCheckBox(self.tab_11)
        self.RT_impose_delay_between_measurements_checkbox_3.setObjectName(u"RT_impose_delay_between_measurements_checkbox_3")
        self.RT_impose_delay_between_measurements_checkbox_3.setGeometry(QRect(40, 230, 301, 20))
        self.RT_impose_delay_between_measurements_textbox_5 = QLineEdit(self.tab_11)
        self.RT_impose_delay_between_measurements_textbox_5.setObjectName(u"RT_impose_delay_between_measurements_textbox_5")
        self.RT_impose_delay_between_measurements_textbox_5.setGeometry(QRect(330, 230, 71, 22))
        self.groupBox_15 = QGroupBox(self.tab_11)
        self.groupBox_15.setObjectName(u"groupBox_15")
        self.groupBox_15.setGeometry(QRect(0, 0, 411, 101))
        self.REAL_T_TRigger_Level_label = QLabel(self.groupBox_15)
        self.REAL_T_TRigger_Level_label.setObjectName(u"REAL_T_TRigger_Level_label")
        self.REAL_T_TRigger_Level_label.setGeometry(QRect(10, 20, 91, 16))
        self.REAL_T_TRigger_Level_textbox = QLineEdit(self.groupBox_15)
        self.REAL_T_TRigger_Level_textbox.setObjectName(u"REAL_T_TRigger_Level_textbox")
        self.REAL_T_TRigger_Level_textbox.setGeometry(QRect(130, 17, 51, 22))
        self.REAL_T_Samp_rate_label_2 = QLabel(self.groupBox_15)
        self.REAL_T_Samp_rate_label_2.setObjectName(u"REAL_T_Samp_rate_label_2")
        self.REAL_T_Samp_rate_label_2.setGeometry(QRect(10, 50, 121, 16))
        self.REAL_T_smp_rate_textbox_2 = QLineEdit(self.groupBox_15)
        self.REAL_T_smp_rate_textbox_2.setObjectName(u"REAL_T_smp_rate_textbox_2")
        self.REAL_T_smp_rate_textbox_2.setGeometry(QRect(130, 47, 51, 22))
        self.REAL_T_Samp_rate_label_3 = QLabel(self.groupBox_15)
        self.REAL_T_Samp_rate_label_3.setObjectName(u"REAL_T_Samp_rate_label_3")
        self.REAL_T_Samp_rate_label_3.setGeometry(QRect(190, 20, 131, 16))
        self.REAL_T_amp_chan_textbox_3 = QLineEdit(self.groupBox_15)
        self.REAL_T_amp_chan_textbox_3.setObjectName(u"REAL_T_amp_chan_textbox_3")
        self.REAL_T_amp_chan_textbox_3.setGeometry(QRect(330, 17, 71, 22))
        self.REAL_T_Samp_rate_label_4 = QLabel(self.groupBox_15)
        self.REAL_T_Samp_rate_label_4.setObjectName(u"REAL_T_Samp_rate_label_4")
        self.REAL_T_Samp_rate_label_4.setGeometry(QRect(190, 50, 131, 16))
        self.REAL_T_trigger_channel_drop_box = QComboBox(self.groupBox_15)
        self.REAL_T_trigger_channel_drop_box.addItem("")
        self.REAL_T_trigger_channel_drop_box.addItem("")
        self.REAL_T_trigger_channel_drop_box.addItem("")
        self.REAL_T_trigger_channel_drop_box.addItem("")
        self.REAL_T_trigger_channel_drop_box.addItem("")
        self.REAL_T_trigger_channel_drop_box.addItem("")
        self.REAL_T_trigger_channel_drop_box.addItem("")
        self.REAL_T_trigger_channel_drop_box.addItem("")
        self.REAL_T_trigger_channel_drop_box.setObjectName(u"REAL_T_trigger_channel_drop_box")
        self.REAL_T_trigger_channel_drop_box.setGeometry(QRect(270, 46, 131, 24))
        self.REAL_T_Samp_rate_label_5 = QLabel(self.groupBox_15)
        self.REAL_T_Samp_rate_label_5.setObjectName(u"REAL_T_Samp_rate_label_5")
        self.REAL_T_Samp_rate_label_5.setGeometry(QRect(10, 80, 121, 16))
        self.REAL_T_PRE_TRigger_durat_textbox_3 = QLineEdit(self.groupBox_15)
        self.REAL_T_PRE_TRigger_durat_textbox_3.setObjectName(u"REAL_T_PRE_TRigger_durat_textbox_3")
        self.REAL_T_PRE_TRigger_durat_textbox_3.setGeometry(QRect(130, 75, 51, 22))
        self.REAL_T_Samp_rate_label_6 = QLabel(self.groupBox_15)
        self.REAL_T_Samp_rate_label_6.setObjectName(u"REAL_T_Samp_rate_label_6")
        self.REAL_T_Samp_rate_label_6.setGeometry(QRect(190, 80, 121, 16))
        self.REAL_Post_trig_durat_textbox_4 = QLineEdit(self.groupBox_15)
        self.REAL_Post_trig_durat_textbox_4.setObjectName(u"REAL_Post_trig_durat_textbox_4")
        self.REAL_Post_trig_durat_textbox_4.setGeometry(QRect(330, 74, 71, 22))
        self.groupBox_16 = QGroupBox(self.tab_11)
        self.groupBox_16.setObjectName(u"groupBox_16")
        self.groupBox_16.setGeometry(QRect(0, 100, 411, 51))
        self.RealT_filse_folders_delete_files_checkbox = QCheckBox(self.groupBox_16)
        self.RealT_filse_folders_delete_files_checkbox.setObjectName(u"RealT_filse_folders_delete_files_checkbox")
        self.RealT_filse_folders_delete_files_checkbox.setGeometry(QRect(10, 20, 211, 20))
        self.RealT_filse_folders_delete_files_checkbox.setChecked(True)
        self.Settings_Spectrograms_Define_Parameters_Tab.addTab(self.tab_11, "")
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.groupBox_10 = QGroupBox(self.tab_6)
        self.groupBox_10.setObjectName(u"groupBox_10")
        self.groupBox_10.setGeometry(QRect(0, 0, 411, 131))
        self.Model_ready_label_2 = QLabel(self.groupBox_10)
        self.Model_ready_label_2.setObjectName(u"Model_ready_label_2")
        self.Model_ready_label_2.setGeometry(QRect(55, 27, 16, 16))
        self.Model_ready_label_2.setAutoFillBackground(True)
        self.Color_list_drop_down_ = QComboBox(self.groupBox_10)
        self.Color_list_drop_down_.addItem("")
        self.Color_list_drop_down_.addItem("")
        self.Color_list_drop_down_.setObjectName(u"Color_list_drop_down_")
        self.Color_list_drop_down_.setGeometry(QRect(46, 20, 121, 24))
        self.COlors_list_show_button = QPushButton(self.groupBox_10)
        self.COlors_list_show_button.setObjectName(u"COlors_list_show_button")
        self.COlors_list_show_button.setGeometry(QRect(258, 20, 75, 24))
        self.Segmentlabel14_2 = QLabel(self.groupBox_10)
        self.Segmentlabel14_2.setObjectName(u"Segmentlabel14_2")
        self.Segmentlabel14_2.setGeometry(QRect(168, 23, 41, 16))
        self.Settings_Segmentation_colors_number_textbox = QLineEdit(self.groupBox_10)
        self.Settings_Segmentation_colors_number_textbox.setObjectName(u"Settings_Segmentation_colors_number_textbox")
        self.Settings_Segmentation_colors_number_textbox.setGeometry(QRect(200, 20, 61, 22))
        self.COlors_list_generate_button = QPushButton(self.groupBox_10)
        self.COlors_list_generate_button.setObjectName(u"COlors_list_generate_button")
        self.COlors_list_generate_button.setGeometry(QRect(329, 20, 81, 24))
        self.Segmentlabel14_3 = QLabel(self.groupBox_10)
        self.Segmentlabel14_3.setObjectName(u"Segmentlabel14_3")
        self.Segmentlabel14_3.setGeometry(QRect(6, 23, 41, 16))
        self.Segmentlabel14_4 = QLabel(self.groupBox_10)
        self.Segmentlabel14_4.setObjectName(u"Segmentlabel14_4")
        self.Segmentlabel14_4.setGeometry(QRect(233, 106, 71, 16))
        self.Show_results_color_scheme_drop_down_1 = QComboBox(self.groupBox_10)
        self.Show_results_color_scheme_drop_down_1.addItem("")
        self.Show_results_color_scheme_drop_down_1.addItem("")
        self.Show_results_color_scheme_drop_down_1.setObjectName(u"Show_results_color_scheme_drop_down_1")
        self.Show_results_color_scheme_drop_down_1.setGeometry(QRect(308, 102, 91, 24))
        self.GUI_show_results_points_number_limit_checkbox = QCheckBox(self.groupBox_10)
        self.GUI_show_results_points_number_limit_checkbox.setObjectName(u"GUI_show_results_points_number_limit_checkbox")
        self.GUI_show_results_points_number_limit_checkbox.setGeometry(QRect(7, 75, 181, 20))
        self.GUI_show_results_points_number_limit_textbox = QLineEdit(self.groupBox_10)
        self.GUI_show_results_points_number_limit_textbox.setObjectName(u"GUI_show_results_points_number_limit_textbox")
        self.GUI_show_results_points_number_limit_textbox.setGeometry(QRect(170, 74, 61, 22))
        self.GUI_mark_segments_checkbox = QCheckBox(self.groupBox_10)
        self.GUI_mark_segments_checkbox.setObjectName(u"GUI_mark_segments_checkbox")
        self.GUI_mark_segments_checkbox.setGeometry(QRect(240, 76, 121, 20))
        self.GUI_impose_delay_checkbox_2 = QCheckBox(self.groupBox_10)
        self.GUI_impose_delay_checkbox_2.setObjectName(u"GUI_impose_delay_checkbox_2")
        self.GUI_impose_delay_checkbox_2.setGeometry(QRect(6, 100, 171, 20))
        self.GUI_impose_measurements_delay_value_textbox_2 = QLineEdit(self.groupBox_10)
        self.GUI_impose_measurements_delay_value_textbox_2.setObjectName(u"GUI_impose_measurements_delay_value_textbox_2")
        self.GUI_impose_measurements_delay_value_textbox_2.setGeometry(QRect(170, 100, 61, 22))
        self.GUI_settitle_figure_checkbox_2 = QCheckBox(self.groupBox_10)
        self.GUI_settitle_figure_checkbox_2.setObjectName(u"GUI_settitle_figure_checkbox_2")
        self.GUI_settitle_figure_checkbox_2.setGeometry(QRect(7, 50, 161, 20))
        self.GUI_fiure_coment_text_2 = QLineEdit(self.groupBox_10)
        self.GUI_fiure_coment_text_2.setObjectName(u"GUI_fiure_coment_text_2")
        self.GUI_fiure_coment_text_2.setGeometry(QRect(160, 50, 241, 22))
        self.groupBox_13 = QGroupBox(self.tab_6)
        self.groupBox_13.setObjectName(u"groupBox_13")
        self.groupBox_13.setGeometry(QRect(0, 130, 411, 101))
        self.Model_ready_label_4 = QLabel(self.groupBox_13)
        self.Model_ready_label_4.setObjectName(u"Model_ready_label_4")
        self.Model_ready_label_4.setGeometry(QRect(55, 27, 16, 16))
        self.Model_ready_label_4.setAutoFillBackground(True)
        self.save_interface_button = QPushButton(self.groupBox_13)
        self.save_interface_button.setObjectName(u"save_interface_button")
        self.save_interface_button.setGeometry(QRect(0, 14, 171, 61))
        self.load_interface_button = QPushButton(self.groupBox_13)
        self.load_interface_button.setObjectName(u"load_interface_button")
        self.load_interface_button.setGeometry(QRect(170, 14, 171, 61))
        self.GUI_load_default_on_start = QCheckBox(self.groupBox_13)
        self.GUI_load_default_on_start.setObjectName(u"GUI_load_default_on_start")
        self.GUI_load_default_on_start.setGeometry(QRect(6, 77, 121, 20))
        self.Settings_Spectrograms_Define_Parameters_Tab.addTab(self.tab_6, "")
        self.tab_7 = QWidget()
        self.tab_7.setObjectName(u"tab_7")
        self.tabWidget_4 = QTabWidget(self.tab_7)
        self.tabWidget_4.setObjectName(u"tabWidget_4")
        self.tabWidget_4.setGeometry(QRect(0, 0, 411, 251))
        self.XGBoost = QWidget()
        self.XGBoost.setObjectName(u"XGBoost")
        self.Settings_Trees_Trees_Number_2 = QLineEdit(self.XGBoost)
        self.Settings_Trees_Trees_Number_2.setObjectName(u"Settings_Trees_Trees_Number_2")
        self.Settings_Trees_Trees_Number_2.setGeometry(QRect(75, 9, 81, 22))
        self.label_28 = QLabel(self.XGBoost)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(10, 12, 91, 16))
        self.label_29 = QLabel(self.XGBoost)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(10, 39, 91, 16))
        self.Settings_Trees_Tree_depth_text_3 = QLineEdit(self.XGBoost)
        self.Settings_Trees_Tree_depth_text_3.setObjectName(u"Settings_Trees_Tree_depth_text_3")
        self.Settings_Trees_Tree_depth_text_3.setGeometry(QRect(75, 34, 81, 22))
        self.label_30 = QLabel(self.XGBoost)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(10, 65, 91, 16))
        self.Settings_Trees_learn_rate_value_text_4 = QLineEdit(self.XGBoost)
        self.Settings_Trees_learn_rate_value_text_4.setObjectName(u"Settings_Trees_learn_rate_value_text_4")
        self.Settings_Trees_learn_rate_value_text_4.setGeometry(QRect(74, 60, 81, 22))
        self.label_31 = QLabel(self.XGBoost)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(10, 94, 171, 16))
        self.Settings_Trees_contaminations_value_text_5 = QLineEdit(self.XGBoost)
        self.Settings_Trees_contaminations_value_text_5.setObjectName(u"Settings_Trees_contaminations_value_text_5")
        self.Settings_Trees_contaminations_value_text_5.setGeometry(QRect(180, 90, 81, 22))
        self.tabWidget_4.addTab(self.XGBoost, "")
        self.tab_9 = QWidget()
        self.tab_9.setObjectName(u"tab_9")
        self.tabWidget_4.addTab(self.tab_9, "")
        self.tab_8 = QWidget()
        self.tab_8.setObjectName(u"tab_8")
        self.label_21 = QLabel(self.tab_8)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(18, 70, 91, 16))
        self.Autoencoder_torch_epochs_num = QLineEdit(self.tab_8)
        self.Autoencoder_torch_epochs_num.setObjectName(u"Autoencoder_torch_epochs_num")
        self.Autoencoder_torch_epochs_num.setGeometry(QRect(90, 68, 81, 22))
        self.label_22 = QLabel(self.tab_8)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(35, 90, 91, 16))
        self.Autoencoder_torch_learn_rate = QLineEdit(self.tab_8)
        self.Autoencoder_torch_learn_rate.setObjectName(u"Autoencoder_torch_learn_rate")
        self.Autoencoder_torch_learn_rate.setGeometry(QRect(90, 89, 81, 22))
        self.groupBox_12 = QGroupBox(self.tab_8)
        self.groupBox_12.setObjectName(u"groupBox_12")
        self.groupBox_12.setGeometry(QRect(0, 0, 131, 41))
        self.Autoencoderbins_text_input = QLineEdit(self.groupBox_12)
        self.Autoencoderbins_text_input.setObjectName(u"Autoencoderbins_text_input")
        self.Autoencoderbins_text_input.setGeometry(QRect(40, 13, 81, 22))
        self.label_23 = QLabel(self.groupBox_12)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(10, 17, 31, 16))
        self.label_20 = QLabel(self.tab_8)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(2, 48, 91, 16))
        self.Autoencoder_torch_threshold_factor = QLineEdit(self.tab_8)
        self.Autoencoder_torch_threshold_factor.setObjectName(u"Autoencoder_torch_threshold_factor")
        self.Autoencoder_torch_threshold_factor.setGeometry(QRect(92, 46, 81, 22))
        self.Autoencoder_set_threshold_button = QPushButton(self.tab_8)
        self.Autoencoder_set_threshold_button.setObjectName(u"Autoencoder_set_threshold_button")
        self.Autoencoder_set_threshold_button.setGeometry(QRect(130, 5, 81, 41))
        self.groupBox_14 = QGroupBox(self.tab_8)
        self.groupBox_14.setObjectName(u"groupBox_14")
        self.groupBox_14.setGeometry(QRect(211, 0, 181, 41))
        self.Autoencoder_ResNet_weight_decay_input_text = QLineEdit(self.groupBox_14)
        self.Autoencoder_ResNet_weight_decay_input_text.setObjectName(u"Autoencoder_ResNet_weight_decay_input_text")
        self.Autoencoder_ResNet_weight_decay_input_text.setGeometry(QRect(89, 13, 81, 22))
        self.label_26 = QLabel(self.groupBox_14)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(10, 17, 81, 16))
        self.tabWidget_4.addTab(self.tab_8, "")
        self.Settings_Spectrograms_Define_Parameters_Tab.addTab(self.tab_7, "")
        self.tab_10 = QWidget()
        self.tab_10.setObjectName(u"tab_10")
        self.groupBox_11 = QGroupBox(self.tab_10)
        self.groupBox_11.setObjectName(u"groupBox_11")
        self.groupBox_11.setGeometry(QRect(240, 0, 171, 51))
        self.Settings_test_MEL_Segment = QPushButton(self.groupBox_11)
        self.Settings_test_MEL_Segment.setObjectName(u"Settings_test_MEL_Segment")
        self.Settings_test_MEL_Segment.setGeometry(QRect(4, 16, 81, 31))
        self.Settings_Test_MEL_snippet = QPushButton(self.groupBox_11)
        self.Settings_Test_MEL_snippet.setObjectName(u"Settings_Test_MEL_snippet")
        self.Settings_Test_MEL_snippet.setGeometry(QRect(84, 15, 81, 31))
        self.Settings_MEL_num_ffts = QLineEdit(self.tab_10)
        self.Settings_MEL_num_ffts.setObjectName(u"Settings_MEL_num_ffts")
        self.Settings_MEL_num_ffts.setGeometry(QRect(65, 21, 61, 22))
        self.label_24 = QLabel(self.tab_10)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(10, 25, 51, 16))
        self.label_27 = QLabel(self.tab_10)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(2, 52, 61, 16))
        self.Settings_MEL_num_MELS_2 = QLineEdit(self.tab_10)
        self.Settings_MEL_num_MELS_2.setObjectName(u"Settings_MEL_num_MELS_2")
        self.Settings_MEL_num_MELS_2.setGeometry(QRect(65, 50, 61, 22))
        self.label_32 = QLabel(self.tab_10)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(0, 80, 61, 16))
        self.Settings_nmfcc_num_MFCC_text = QLineEdit(self.tab_10)
        self.Settings_nmfcc_num_MFCC_text.setObjectName(u"Settings_nmfcc_num_MFCC_text")
        self.Settings_nmfcc_num_MFCC_text.setGeometry(QRect(66, 77, 61, 22))
        self.Settings_Spectrograms_Define_Parameters_Tab.addTab(self.tab_10, "")
        self.tabWidget.addTab(self.tab_3, "")
        self.Settings_Spectrograms_Define_Parameters_Tab.raise_()
        self.groupBox_8.raise_()
        self.groupBox_9 = QGroupBox(self.centralwidget)
        self.groupBox_9.setObjectName(u"groupBox_9")
        self.groupBox_9.setGeometry(QRect(0, 0, 421, 81))
        self.label_14 = QLabel(self.groupBox_9)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 27, 41, 16))
        self.Model_ready_label = QLabel(self.groupBox_9)
        self.Model_ready_label.setObjectName(u"Model_ready_label")
        self.Model_ready_label.setGeometry(QRect(55, 27, 16, 16))
        self.Model_ready_label.setAutoFillBackground(True)
        self.label_10 = QLabel(self.groupBox_9)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(80, 14, 51, 16))
        self.classification_snippet_size_text = QLineEdit(self.groupBox_9)
        self.classification_snippet_size_text.setObjectName(u"classification_snippet_size_text")
        self.classification_snippet_size_text.setGeometry(QRect(126, 11, 101, 22))
        self.classification_preproc_dropdown = QComboBox(self.groupBox_9)
        self.classification_preproc_dropdown.addItem("")
        self.classification_preproc_dropdown.addItem("")
        self.classification_preproc_dropdown.addItem("")
        self.classification_preproc_dropdown.addItem("")
        self.classification_preproc_dropdown.addItem("")
        self.classification_preproc_dropdown.addItem("")
        self.classification_preproc_dropdown.addItem("")
        self.classification_preproc_dropdown.addItem("")
        self.classification_preproc_dropdown.addItem("")
        self.classification_preproc_dropdown.addItem("")
        self.classification_preproc_dropdown.addItem("")
        self.classification_preproc_dropdown.setObjectName(u"classification_preproc_dropdown")
        self.classification_preproc_dropdown.setGeometry(QRect(126, 33, 101, 24))
        self.label_15 = QLabel(self.groupBox_9)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(80, 35, 50, 16))
        self.label_25 = QLabel(self.groupBox_9)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(3, 60, 91, 16))
        self.classification_channels_choice_drop_down = QComboBox(self.groupBox_9)
        self.classification_channels_choice_drop_down.addItem("")
        self.classification_channels_choice_drop_down.addItem("")
        self.classification_channels_choice_drop_down.setObjectName(u"classification_channels_choice_drop_down")
        self.classification_channels_choice_drop_down.setGeometry(QRect(60, 55, 231, 24))
        self.classification_user_channels_text_box = QLineEdit(self.groupBox_9)
        self.classification_user_channels_text_box.setObjectName(u"classification_user_channels_text_box")
        self.classification_user_channels_text_box.setGeometry(QRect(292, 55, 111, 22))
        EmpaGUI.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(EmpaGUI)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 431, 33))
        EmpaGUI.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(EmpaGUI)
        self.statusbar.setObjectName(u"statusbar")
        EmpaGUI.setStatusBar(self.statusbar)

        self.retranslateUi(EmpaGUI)

        self.tabWidget.setCurrentIndex(1)
        self.load_data_plate_type_dropdown.setCurrentIndex(-1)
        self.real_time_source_dropdown_2.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(1)
        self.classification_preproc_dropdown_4.setCurrentIndex(0)
        self.classificationclassifier_dropdown.setCurrentIndex(0)
        self.classification_preproc_dropdown_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        self.classification_plot_choice_dropdown_3.setCurrentIndex(0)
        self.Settings_openfile_segmentation_mode_text.setCurrentIndex(0)
        self.Settings_Spectrograms_Define_Parameters_Tab.setCurrentIndex(1)
        self.REAL_T_trigger_channel_drop_box.setCurrentIndex(7)
        self.Color_list_drop_down_.setCurrentIndex(0)
        self.Show_results_color_scheme_drop_down_1.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)
        self.classification_preproc_dropdown.setCurrentIndex(-1)
        self.classification_channels_choice_drop_down.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(EmpaGUI)
    # setupUi

    def retranslateUi(self, EmpaGUI):
        EmpaGUI.setWindowTitle(QCoreApplication.translate("EmpaGUI", u"MainWindow", None))
        self.groupBox.setTitle(QCoreApplication.translate("EmpaGUI", u"Load data", None))
        self.load_data_path.setText(QCoreApplication.translate("EmpaGUI", u"C:\\SERGEY\\ANDRITZ_DATA\\trial", None))
        self.Brows_data_folder_button.setText(QCoreApplication.translate("EmpaGUI", u"Browse folder", None))
        self.load_data_plate_type_dropdown.setItemText(0, QCoreApplication.translate("EmpaGUI", u"default", None))
        self.load_data_plate_type_dropdown.setItemText(1, QCoreApplication.translate("EmpaGUI", u"bpp", None))
        self.load_data_plate_type_dropdown.setItemText(2, QCoreApplication.translate("EmpaGUI", u"long_bpp_1", None))
        self.load_data_plate_type_dropdown.setItemText(3, QCoreApplication.translate("EmpaGUI", u"long_bpp_2", None))
        self.load_data_plate_type_dropdown.setItemText(4, QCoreApplication.translate("EmpaGUI", u"from file", None))

        self.load_data_plate_type_dropdown.setCurrentText("")
        self.load_data_plate_type_dropdown.setPlaceholderText(QCoreApplication.translate("EmpaGUI", u"default", None))
        self.load_data_button.setText(QCoreApplication.translate("EmpaGUI", u"Load", None))
        self.label.setText(QCoreApplication.translate("EmpaGUI", u"Plate layout:", None))
        self.List_segments_names_button.setText(QCoreApplication.translate("EmpaGUI", u"Check segm.list", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("EmpaGUI", u"Real time", None))
        self.real_time_source_dropdown_2.setItemText(0, QCoreApplication.translate("EmpaGUI", u"Folder", None))
        self.real_time_source_dropdown_2.setItemText(1, QCoreApplication.translate("EmpaGUI", u"RealTime", None))

        self.real_time_source_dropdown_2.setCurrentText(QCoreApplication.translate("EmpaGUI", u"RealTime", None))
        self.real_time_source_dropdown_2.setPlaceholderText(QCoreApplication.translate("EmpaGUI", u"RealTime", None))
        self.Brows_data_folder_button_2.setText(QCoreApplication.translate("EmpaGUI", u"Browse folder", None))
        self.real_time_folder_text.setText(QCoreApplication.translate("EmpaGUI", u"C:\\SERGEY\\ANDRITZ_DATA\\REAL_TIME_FOLDER", None))
        self.Start_real_time_button.setText(QCoreApplication.translate("EmpaGUI", u"Run real-time", None))
        self.Stop_real_time_button_2.setText(QCoreApplication.translate("EmpaGUI", u"Stop real-time", None))
        self.label_18.setText(QCoreApplication.translate("EmpaGUI", u"Frame counter:", None))
        self.Real_time_Frame_counter_label.setText(QCoreApplication.translate("EmpaGUI", u"0", None))
        self.label_19.setText(QCoreApplication.translate("EmpaGUI", u"Status:", None))
        self.real_time_status_label.setText(QCoreApplication.translate("EmpaGUI", u"Not active", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("EmpaGUI", u"Main", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("EmpaGUI", u"Segments", None))
        self.plot_plate_dropdown.setPlaceholderText(QCoreApplication.translate("EmpaGUI", u"Choose plate to plot", None))
        self.plot_segment_dropdown.setPlaceholderText(QCoreApplication.translate("EmpaGUI", u"Choose segment to plot", None))
        self.plot_button.setText(QCoreApplication.translate("EmpaGUI", u"Plot signal", None))
        self.platre_data_button_2.setText(QCoreApplication.translate("EmpaGUI", u"Info", None))
        self.Channel_segment_plot.setPlaceholderText(QCoreApplication.translate("EmpaGUI", u"Choose channel to plot", None))
        self.type_of_signal_dropdown.setItemText(0, QCoreApplication.translate("EmpaGUI", u"Raw signals", None))
        self.type_of_signal_dropdown.setItemText(1, QCoreApplication.translate("EmpaGUI", u"Segments", None))

        self.type_of_signal_dropdown.setPlaceholderText(QCoreApplication.translate("EmpaGUI", u"Choose segment to plot", None))
        self.label_2.setText(QCoreApplication.translate("EmpaGUI", u"Plate:", None))
        self.label_3.setText(QCoreApplication.translate("EmpaGUI", u"Type:", None))
        self.label_4.setText(QCoreApplication.translate("EmpaGUI", u"Segment:", None))
        self.label_5.setText(QCoreApplication.translate("EmpaGUI", u"Channel:", None))
        self.unload_as_csv_button_data_button_3.setText(QCoreApplication.translate("EmpaGUI", u"Save as *.SCV", None))
        self.tools_show_scpetrogram_button.setText(QCoreApplication.translate("EmpaGUI", u"Show", None))
        self.classification_preproc_dropdown_4.setItemText(0, QCoreApplication.translate("EmpaGUI", u"MEL", None))

        self.classification_preproc_dropdown_4.setCurrentText(QCoreApplication.translate("EmpaGUI", u"MEL", None))
        self.classification_preproc_dropdown_4.setPlaceholderText(QCoreApplication.translate("EmpaGUI", u"None", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("EmpaGUI", u"Classification ", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("EmpaGUI", u"Classification train/test", None))
        self.classification_run_classification_button.setText(QCoreApplication.translate("EmpaGUI", u"Train", None))
        self.label_13.setText(QCoreApplication.translate("EmpaGUI", u"Model:", None))
        self.classificationclassifier_dropdown.setItemText(0, QCoreApplication.translate("EmpaGUI", u"XGBoost", None))
        self.classificationclassifier_dropdown.setItemText(1, QCoreApplication.translate("EmpaGUI", u"IsolationForest", None))
        self.classificationclassifier_dropdown.setItemText(2, QCoreApplication.translate("EmpaGUI", u"DBSCAN", None))
        self.classificationclassifier_dropdown.setItemText(3, QCoreApplication.translate("EmpaGUI", u"OneClassSVM", None))
        self.classificationclassifier_dropdown.setItemText(4, QCoreApplication.translate("EmpaGUI", u"Autoencoder_1", None))
        self.classificationclassifier_dropdown.setItemText(5, QCoreApplication.translate("EmpaGUI", u"Autoencoder_2", None))
        self.classificationclassifier_dropdown.setItemText(6, QCoreApplication.translate("EmpaGUI", u"AE_CNN_Shallow", None))
        self.classificationclassifier_dropdown.setItemText(7, QCoreApplication.translate("EmpaGUI", u"ResNet_Shallow", None))
        self.classificationclassifier_dropdown.setItemText(8, QCoreApplication.translate("EmpaGUI", u"NonStatKern_1", None))
        self.classificationclassifier_dropdown.setItemText(9, QCoreApplication.translate("EmpaGUI", u"GHKern", None))

        self.classificationclassifier_dropdown.setPlaceholderText(QCoreApplication.translate("EmpaGUI", u"XGBoost", None))
        self.label_11.setText(QCoreApplication.translate("EmpaGUI", u"Test (%):", None))
        self.classification_test_text.setText(QCoreApplication.translate("EmpaGUI", u"20", None))
        self.classification_dataset_info_button.setText(QCoreApplication.translate("EmpaGUI", u"Info", None))
        self.Classification_extract_save_features_to_file_button.setText(QCoreApplication.translate("EmpaGUI", u"Save feat. to file", None))
        self.Classification_run_test_on_complete_segment_button.setText(QCoreApplication.translate("EmpaGUI", u"Test segment", None))
        self.label_17.setText(QCoreApplication.translate("EmpaGUI", u"Apply to:", None))
        self.classification_preproc_dropdown_2.setItemText(0, QCoreApplication.translate("EmpaGUI", u"this_plate_this_segment", None))
        self.classification_preproc_dropdown_2.setItemText(1, QCoreApplication.translate("EmpaGUI", u"this_plate_all_segments", None))
        self.classification_preproc_dropdown_2.setItemText(2, QCoreApplication.translate("EmpaGUI", u"all_plates_all_segments", None))

        self.classification_preproc_dropdown_2.setCurrentText(QCoreApplication.translate("EmpaGUI", u"this_plate_this_segment", None))
        self.classification_preproc_dropdown_2.setPlaceholderText(QCoreApplication.translate("EmpaGUI", u"this_plate_this_segment", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("EmpaGUI", u"Labeling", None))
        self.classification_set_category.setText(QCoreApplication.translate("EmpaGUI", u"Assign", None))
        self.label_7.setText(QCoreApplication.translate("EmpaGUI", u"end-", None))
        self.label_8.setText(QCoreApplication.translate("EmpaGUI", u"label-", None))
        self.label_9.setText(QCoreApplication.translate("EmpaGUI", u"Start:", None))
        self.classification_clear_labels_button.setText(QCoreApplication.translate("EmpaGUI", u"Clear", None))
        self.calssification_segment_savetofolder_button.setText(QCoreApplication.translate("EmpaGUI", u"Save lab. data (.csv)", None))
        self.classification_entire_segment_to_label_button.setText(QCoreApplication.translate("EmpaGUI", u"Segment<->Label", None))
        self.classification_all_segments_to_label_button_2.setText(QCoreApplication.translate("EmpaGUI", u"All segments<->Label", None))
        self.classification_clear_all_segments_labels_button_2.setText(QCoreApplication.translate("EmpaGUI", u"Clear all", None))
        self.calssification_plot_segment.setText(QCoreApplication.translate("EmpaGUI", u"Plot", None))
        self.classification_plot_choice_dropdown_3.setItemText(0, QCoreApplication.translate("EmpaGUI", u"Segment", None))
        self.classification_plot_choice_dropdown_3.setItemText(1, QCoreApplication.translate("EmpaGUI", u"All_segments", None))

        self.classification_plot_choice_dropdown_3.setCurrentText(QCoreApplication.translate("EmpaGUI", u"Segment", None))
        self.classification_plot_choice_dropdown_3.setPlaceholderText(QCoreApplication.translate("EmpaGUI", u"this_plate_this_segment", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_12), QCoreApplication.translate("EmpaGUI", u"Main", None))
        self.Classification_save_to_file_labeling_button.setText(QCoreApplication.translate("EmpaGUI", u"Save labelling to file", None))
        self.Classification_load_from_file_labeling_button_2.setText(QCoreApplication.translate("EmpaGUI", u"Load labelling from file", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("EmpaGUI", u"Model", None))
        self.load_model_button.setText(QCoreApplication.translate("EmpaGUI", u"Load", None))
        self.train_dropdown.setItemText(0, QCoreApplication.translate("EmpaGUI", u"XGBoost", None))
        self.train_dropdown.setItemText(1, QCoreApplication.translate("EmpaGUI", u"Autoencoder", None))

        self.train_dropdown.setCurrentText("")
        self.train_dropdown.setPlaceholderText(QCoreApplication.translate("EmpaGUI", u"Autoencoder", None))
        self.label_16.setText(QCoreApplication.translate("EmpaGUI", u"Model type:", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_13), QCoreApplication.translate("EmpaGUI", u"Add-onn", None))
        self.groupBox_17.setTitle(QCoreApplication.translate("EmpaGUI", u"No labels (labels will not be preserved)", None))
        self.Classification_save__all_plates_segm_to_file_labeling_button_2.setText(QCoreApplication.translate("EmpaGUI", u"Save all plates segments  into file", None))
        self.Classification_load__all_plates_segm_to_file_labeling_button_2.setText(QCoreApplication.translate("EmpaGUI", u"Load all plates segments  into file", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_14), QCoreApplication.translate("EmpaGUI", u"Add-onn(1)", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), QCoreApplication.translate("EmpaGUI", u"Page 1", None))
        self.groupBox_18.setTitle(QCoreApplication.translate("EmpaGUI", u"Search best params", None))
        self.label_6.setText(QCoreApplication.translate("EmpaGUI", u"Store results folder:", None))
        self.Tool_start_best_param_search_button_2.setText(QCoreApplication.translate("EmpaGUI", u"Start procedure", None))
        self.Tools_best_params_search_folder_path_text_2.setText(QCoreApplication.translate("EmpaGUI", u"C:\\\\tmp", None))
        self.Brows_data_folder_button_3.setText(QCoreApplication.translate("EmpaGUI", u"Browse", None))
        self.label_33.setText(QCoreApplication.translate("EmpaGUI", u"Snippet size - start:", None))
        self.Tools_best_params_search_snippet_size_start_text_3.setText(QCoreApplication.translate("EmpaGUI", u"50", None))
        self.label_34.setText(QCoreApplication.translate("EmpaGUI", u"end:", None))
        self.Tools_best_params_search_snippet_size_end_text_3.setText(QCoreApplication.translate("EmpaGUI", u"4000", None))
        self.label_35.setText(QCoreApplication.translate("EmpaGUI", u"step:", None))
        self.Tools_best_params_search_snippet_size_step_text_3.setText(QCoreApplication.translate("EmpaGUI", u"200", None))
        self.label_36.setText(QCoreApplication.translate("EmpaGUI", u"Channels:", None))
        self.Tools_best_params_search_channels_list_text_3.setText(QCoreApplication.translate("EmpaGUI", u"0,1,3", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), QCoreApplication.translate("EmpaGUI", u"Page 2", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("EmpaGUI", u"Tools", None))
        self.groupBox_8.setTitle(QCoreApplication.translate("EmpaGUI", u"Train data source", None))
        self.label_12.setText(QCoreApplication.translate("EmpaGUI", u"Trigger chan.(name or number):", None))
        self.Settings_OpenFile_TrigChannelID_text.setText(QCoreApplication.translate("EmpaGUI", u"Trigger", None))
        self.Segmentlabel14.setText(QCoreApplication.translate("EmpaGUI", u"Segmentation mode:", None))
        self.Settings_openfile_segmentation_mode_text.setItemText(0, QCoreApplication.translate("EmpaGUI", u"automatic", None))
        self.Settings_openfile_segmentation_mode_text.setItemText(1, QCoreApplication.translate("EmpaGUI", u"user defined thershold:", None))

        self.Settings_openfile_segmentation_mode_text.setCurrentText(QCoreApplication.translate("EmpaGUI", u"automatic", None))
        self.Settings_openfile_segmentation_mode_text.setPlaceholderText(QCoreApplication.translate("EmpaGUI", u"Choose BPP type", None))
        self.Settings_Segmentation_TriggerThreshold_text.setText(QCoreApplication.translate("EmpaGUI", u"Trigger", None))
        self.RealT_show_info_checkbox.setText(QCoreApplication.translate("EmpaGUI", u"Show info", None))
        self.RealT_show_processed_signals_checkbox_3.setText(QCoreApplication.translate("EmpaGUI", u"Show processed signals", None))
        self.RealT_show_only_single_shot_checkbox_4.setText(QCoreApplication.translate("EmpaGUI", u"Only single shot", None))
        self.RT_impose_delay_between_measurements_checkbox_3.setText(QCoreApplication.translate("EmpaGUI", u"Impose display delay between measurements (ms):", None))
        self.RT_impose_delay_between_measurements_textbox_5.setText(QCoreApplication.translate("EmpaGUI", u"100", None))
        self.groupBox_15.setTitle(QCoreApplication.translate("EmpaGUI", u"Spectrum DAQ", None))
        self.REAL_T_TRigger_Level_label.setText(QCoreApplication.translate("EmpaGUI", u"Trigger lev.(mV):", None))
        self.REAL_T_TRigger_Level_textbox.setText(QCoreApplication.translate("EmpaGUI", u"2500", None))
        self.REAL_T_Samp_rate_label_2.setText(QCoreApplication.translate("EmpaGUI", u"Sampling rate (MHz):", None))
        self.REAL_T_smp_rate_textbox_2.setText(QCoreApplication.translate("EmpaGUI", u"0.5", None))
        self.REAL_T_Samp_rate_label_3.setText(QCoreApplication.translate("EmpaGUI", u"Amplitude/channel(mV):", None))
        self.REAL_T_amp_chan_textbox_3.setText(QCoreApplication.translate("EmpaGUI", u"5000", None))
        self.REAL_T_Samp_rate_label_4.setText(QCoreApplication.translate("EmpaGUI", u"Trigger chan.:", None))
        self.REAL_T_trigger_channel_drop_box.setItemText(0, QCoreApplication.translate("EmpaGUI", u"0", None))
        self.REAL_T_trigger_channel_drop_box.setItemText(1, QCoreApplication.translate("EmpaGUI", u"1", None))
        self.REAL_T_trigger_channel_drop_box.setItemText(2, QCoreApplication.translate("EmpaGUI", u"2", None))
        self.REAL_T_trigger_channel_drop_box.setItemText(3, QCoreApplication.translate("EmpaGUI", u"3", None))
        self.REAL_T_trigger_channel_drop_box.setItemText(4, QCoreApplication.translate("EmpaGUI", u"4", None))
        self.REAL_T_trigger_channel_drop_box.setItemText(5, QCoreApplication.translate("EmpaGUI", u"5", None))
        self.REAL_T_trigger_channel_drop_box.setItemText(6, QCoreApplication.translate("EmpaGUI", u"6", None))
        self.REAL_T_trigger_channel_drop_box.setItemText(7, QCoreApplication.translate("EmpaGUI", u"7", None))

        self.REAL_T_trigger_channel_drop_box.setCurrentText(QCoreApplication.translate("EmpaGUI", u"7", None))
        self.REAL_T_trigger_channel_drop_box.setPlaceholderText(QCoreApplication.translate("EmpaGUI", u"Choose BPP type", None))
        self.REAL_T_Samp_rate_label_5.setText(QCoreApplication.translate("EmpaGUI", u"Pre-trig. durat(ms):", None))
        self.REAL_T_PRE_TRigger_durat_textbox_3.setText(QCoreApplication.translate("EmpaGUI", u"10", None))
        self.REAL_T_Samp_rate_label_6.setText(QCoreApplication.translate("EmpaGUI", u"Post trig.durat(ms)", None))
        self.REAL_Post_trig_durat_textbox_4.setText(QCoreApplication.translate("EmpaGUI", u"100", None))
        self.groupBox_16.setTitle(QCoreApplication.translate("EmpaGUI", u"Files/folders", None))
        self.RealT_filse_folders_delete_files_checkbox.setText(QCoreApplication.translate("EmpaGUI", u"Delete files after processing", None))
        self.Settings_Spectrograms_Define_Parameters_Tab.setTabText(self.Settings_Spectrograms_Define_Parameters_Tab.indexOf(self.tab_11), QCoreApplication.translate("EmpaGUI", u"Real time", None))
        self.groupBox_10.setTitle(QCoreApplication.translate("EmpaGUI", u"Processing results show", None))
        self.Model_ready_label_2.setText("")
        self.Color_list_drop_down_.setItemText(0, QCoreApplication.translate("EmpaGUI", u"Grades of red", None))
        self.Color_list_drop_down_.setItemText(1, QCoreApplication.translate("EmpaGUI", u"Random colors", None))

        self.Color_list_drop_down_.setCurrentText(QCoreApplication.translate("EmpaGUI", u"Grades of red", None))
        self.Color_list_drop_down_.setPlaceholderText(QCoreApplication.translate("EmpaGUI", u"None", None))
        self.COlors_list_show_button.setText(QCoreApplication.translate("EmpaGUI", u"Show colors", None))
        self.Segmentlabel14_2.setText(QCoreApplication.translate("EmpaGUI", u"Num.:", None))
        self.Settings_Segmentation_colors_number_textbox.setText(QCoreApplication.translate("EmpaGUI", u"15", None))
        self.COlors_list_generate_button.setText(QCoreApplication.translate("EmpaGUI", u"Update", None))
        self.Segmentlabel14_3.setText(QCoreApplication.translate("EmpaGUI", u"Colors:", None))
        self.Segmentlabel14_4.setText(QCoreApplication.translate("EmpaGUI", u"Show results:", None))
        self.Show_results_color_scheme_drop_down_1.setItemText(0, QCoreApplication.translate("EmpaGUI", u"all_grades", None))
        self.Show_results_color_scheme_drop_down_1.setItemText(1, QCoreApplication.translate("EmpaGUI", u"only_anom", None))

        self.Show_results_color_scheme_drop_down_1.setCurrentText(QCoreApplication.translate("EmpaGUI", u"all_grades", None))
        self.Show_results_color_scheme_drop_down_1.setPlaceholderText(QCoreApplication.translate("EmpaGUI", u"Grades of red", None))
        self.GUI_show_results_points_number_limit_checkbox.setText(QCoreApplication.translate("EmpaGUI", u"Set points number limit to:", None))
        self.GUI_show_results_points_number_limit_textbox.setText(QCoreApplication.translate("EmpaGUI", u"3000", None))
        self.GUI_mark_segments_checkbox.setText(QCoreApplication.translate("EmpaGUI", u"Mark segments", None))
        self.GUI_impose_delay_checkbox_2.setText(QCoreApplication.translate("EmpaGUI", u"Impose display delay (ms):", None))
        self.GUI_impose_measurements_delay_value_textbox_2.setText(QCoreApplication.translate("EmpaGUI", u"200", None))
        self.GUI_settitle_figure_checkbox_2.setText(QCoreApplication.translate("EmpaGUI", u"Add comment to figure:", None))
        self.GUI_fiure_coment_text_2.setText(QCoreApplication.translate("EmpaGUI", u"Trigger", None))
        self.groupBox_13.setTitle(QCoreApplication.translate("EmpaGUI", u"GUI save/load", None))
        self.Model_ready_label_4.setText("")
        self.save_interface_button.setText(QCoreApplication.translate("EmpaGUI", u"Save interface", None))
        self.load_interface_button.setText(QCoreApplication.translate("EmpaGUI", u"Load interface", None))
        self.GUI_load_default_on_start.setText(QCoreApplication.translate("EmpaGUI", u"Load on start", None))
        self.Settings_Spectrograms_Define_Parameters_Tab.setTabText(self.Settings_Spectrograms_Define_Parameters_Tab.indexOf(self.tab_6), QCoreApplication.translate("EmpaGUI", u"GUI", None))
        self.Settings_Trees_Trees_Number_2.setText(QCoreApplication.translate("EmpaGUI", u"800", None))
        self.label_28.setText(QCoreApplication.translate("EmpaGUI", u"Trees num.:", None))
        self.label_29.setText(QCoreApplication.translate("EmpaGUI", u"Tree depth:", None))
        self.Settings_Trees_Tree_depth_text_3.setText(QCoreApplication.translate("EmpaGUI", u"12", None))
        self.label_30.setText(QCoreApplication.translate("EmpaGUI", u"Learn rate:", None))
        self.Settings_Trees_learn_rate_value_text_4.setText(QCoreApplication.translate("EmpaGUI", u"0.01", None))
        self.label_31.setText(QCoreApplication.translate("EmpaGUI", u"Contamination(Isolation trees):", None))
        self.Settings_Trees_contaminations_value_text_5.setText(QCoreApplication.translate("EmpaGUI", u"0.1", None))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.XGBoost), QCoreApplication.translate("EmpaGUI", u"XGBoost/Trees", None))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_9), QCoreApplication.translate("EmpaGUI", u"SVM", None))
        self.label_21.setText(QCoreApplication.translate("EmpaGUI", u"Epochs num.:", None))
        self.Autoencoder_torch_epochs_num.setText(QCoreApplication.translate("EmpaGUI", u"100", None))
        self.label_22.setText(QCoreApplication.translate("EmpaGUI", u"Learn rate:", None))
        self.Autoencoder_torch_learn_rate.setText(QCoreApplication.translate("EmpaGUI", u"0.00005", None))
        self.groupBox_12.setTitle(QCoreApplication.translate("EmpaGUI", u"Autoencoder 1", None))
        self.Autoencoderbins_text_input.setText(QCoreApplication.translate("EmpaGUI", u"50", None))
        self.label_23.setText(QCoreApplication.translate("EmpaGUI", u"Bins:", None))
        self.label_20.setText(QCoreApplication.translate("EmpaGUI", u"Threshold factor:", None))
        self.Autoencoder_torch_threshold_factor.setText(QCoreApplication.translate("EmpaGUI", u"3.5", None))
        self.Autoencoder_set_threshold_button.setText(QCoreApplication.translate("EmpaGUI", u"Set/test", None))
        self.groupBox_14.setTitle(QCoreApplication.translate("EmpaGUI", u"ResNet_AutoEncoder", None))
        self.Autoencoder_ResNet_weight_decay_input_text.setText(QCoreApplication.translate("EmpaGUI", u"0.01", None))
        self.label_26.setText(QCoreApplication.translate("EmpaGUI", u"Weight decay:", None))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_8), QCoreApplication.translate("EmpaGUI", u"Autoencoder", None))
        self.Settings_Spectrograms_Define_Parameters_Tab.setTabText(self.Settings_Spectrograms_Define_Parameters_Tab.indexOf(self.tab_7), QCoreApplication.translate("EmpaGUI", u"Classifier", None))
        self.groupBox_11.setTitle(QCoreApplication.translate("EmpaGUI", u"MEL spectrogram", None))
        self.Settings_test_MEL_Segment.setText(QCoreApplication.translate("EmpaGUI", u"Test segment", None))
        self.Settings_Test_MEL_snippet.setText(QCoreApplication.translate("EmpaGUI", u"Test snippet", None))
        self.Settings_MEL_num_ffts.setText(QCoreApplication.translate("EmpaGUI", u"128", None))
        self.label_24.setText(QCoreApplication.translate("EmpaGUI", u"Num.ffts:", None))
        self.label_27.setText(QCoreApplication.translate("EmpaGUI", u"Num.MELs:", None))
        self.Settings_MEL_num_MELS_2.setText(QCoreApplication.translate("EmpaGUI", u"512", None))
        self.label_32.setText(QCoreApplication.translate("EmpaGUI", u"Num.mFCC:", None))
        self.Settings_nmfcc_num_MFCC_text.setText(QCoreApplication.translate("EmpaGUI", u"13", None))
        self.Settings_Spectrograms_Define_Parameters_Tab.setTabText(self.Settings_Spectrograms_Define_Parameters_Tab.indexOf(self.tab_10), QCoreApplication.translate("EmpaGUI", u"Spectrograms", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("EmpaGUI", u"Settings", None))
        self.groupBox_9.setTitle(QCoreApplication.translate("EmpaGUI", u"Globals", None))
        self.label_14.setText(QCoreApplication.translate("EmpaGUI", u"Model:", None))
        self.Model_ready_label.setText("")
        self.label_10.setText(QCoreApplication.translate("EmpaGUI", u"Snippet:", None))
        self.classification_snippet_size_text.setText(QCoreApplication.translate("EmpaGUI", u"1000", None))
        self.classification_preproc_dropdown.setItemText(0, QCoreApplication.translate("EmpaGUI", u"None", None))
        self.classification_preproc_dropdown.setItemText(1, QCoreApplication.translate("EmpaGUI", u"torch_MEL", None))
        self.classification_preproc_dropdown.setItemText(2, QCoreApplication.translate("EmpaGUI", u"torch_MEL_rel", None))
        self.classification_preproc_dropdown.setItemText(3, QCoreApplication.translate("EmpaGUI", u"torch_FFT", None))
        self.classification_preproc_dropdown.setItemText(4, QCoreApplication.translate("EmpaGUI", u"torch_FFT_rel", None))
        self.classification_preproc_dropdown.setItemText(5, QCoreApplication.translate("EmpaGUI", u"torch_MFCC", None))
        self.classification_preproc_dropdown.setItemText(6, QCoreApplication.translate("EmpaGUI", u"torch_WFFT", None))
        self.classification_preproc_dropdown.setItemText(7, QCoreApplication.translate("EmpaGUI", u"torch_GrifLim", None))
        self.classification_preproc_dropdown.setItemText(8, QCoreApplication.translate("EmpaGUI", u"torch_LFCC", None))
        self.classification_preproc_dropdown.setItemText(9, QCoreApplication.translate("EmpaGUI", u"torch_SpecCentr", None))
        self.classification_preproc_dropdown.setItemText(10, QCoreApplication.translate("EmpaGUI", u"tocrh_DWT", None))

        self.classification_preproc_dropdown.setCurrentText("")
        self.classification_preproc_dropdown.setPlaceholderText(QCoreApplication.translate("EmpaGUI", u"None", None))
        self.label_15.setText(QCoreApplication.translate("EmpaGUI", u"Preproc.:", None))
        self.label_25.setText(QCoreApplication.translate("EmpaGUI", u"Channels:", None))
        self.classification_channels_choice_drop_down.setItemText(0, QCoreApplication.translate("EmpaGUI", u"From settings", None))
        self.classification_channels_choice_drop_down.setItemText(1, QCoreApplication.translate("EmpaGUI", u"User defined (\",\" as separator)->:", None))

        self.classification_channels_choice_drop_down.setCurrentText(QCoreApplication.translate("EmpaGUI", u"From settings", None))
        self.classification_channels_choice_drop_down.setPlaceholderText(QCoreApplication.translate("EmpaGUI", u"this_plate_this_segment", None))
        self.classification_user_channels_text_box.setText(QCoreApplication.translate("EmpaGUI", u"0,1,3", None))
    # retranslateUi

